server:
  port: 8080
  context-path: /api

#user-service:
#  ribbon:
#    listOfServers: localhost:8082

zuul:
  ignored-services: "*"
  sensitive-headers:
  routes:
    user:
      path: /users/**
      serviceId: userService
      stripPrefix: false
    session:
      path: /login/**
      serviceId: userService
      stripPrefix: false
    todos:
      path: /todos/**
      #url: todoService
      serviceId: todoService

spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckPath: /api/health

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
