server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/todo_m?createDatabaseIfNotExist=true
    username: root
    password: 123swl
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

zuul:
  ignored-services: "*"
  sensitive-headers:
  routes:
    user:
      path: /users/**
      url: localhost:8082/users/
      stripPrefix: false
    login:
      path: /login/**
      url: localhost:8082/login/
      stripPrefix: false
