server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_m_db?createDatabaseIfNotExist=true
    username: root
    password: 123swl
  jpa:
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans:false

zuul:
  ignored-services: "*"
  sensitive-headers:
  routes:
    user:
      path: /users/**
      url: http://localhost:8082
      stripPrefix: false
