server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/todo_m
    username: root
    password: 123swl
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckPath: /health

#user-service:
 # ribbon:
  #  listOfServers: localhost:8082

zuul:
  ignored-services: "*"
  sensitive-headers:
  routes:
    user:
      path: /users/**
      serviceId: userService
      stripPrefix: false
